name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - run: go build -o hud main.go

      - uses: softprops/action-gh-release@v1
        with:
          files: hud
